# Generated by Django 6.0.2 on 2026-02-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson21', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
