# Generated by Django 6.0.2 on 2026-02-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0001_initial'),
    ]

    operations = [
    ]
