# Generated by Django 6.0.2 on 2026-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Jan Nowak', max_length=100),
            preserve_default=False,
        ),
    ]
